# =====================================================================
# Script      : New-UHMDMWiFiTemplate.ps1
# Author      : Jeffrey Altomari
# Date        : 06-17-2026
# Version     : 2.1.0
#
# Description : Creates, validates, and optionally publishes a UH MDM /
#               WiFi device certificate template in AD CS using the
#               supported CertEnroll COM template authoring path
#               (IX509CertificateTemplateWritable) together with the
#               PSPKI module. The template is cloned from a known-good
#               V2 base (Workstation Authentication), the OID object is
#               auto-generated by the platform on Commit, and the
#               device-cert deltas are applied (supply-in-request
#               subject, Client Authentication EKU, optional Server
#               Authentication EKU). Permissions are granted and the
#               template is published using PSPKI cmdlets.
#               Original concept and field work by Jeffrey Altomari;
#               rebuilt to the UH canonical PowerShell standard.
#
# Requirements: PowerShell 5.1; PSPKI module (auto-installed from PSGallery);
#               CertEnroll COM (built into Windows); Enterprise Admin
#               (or delegated) rights on the Configuration partition to
#               author templates; rights on the issuing CA to publish;
#               network access to a DC and to smtp.uhhs.com:25.
#
# Change Log:#
#   1.0.0 - 2026-06-17 - Initial canonical rewrite of Jeffrey Altomari's
#                        UH-WDM-WiFi_Template_Creation.ps1.
#                        Switched default base template from User (V1) to
#                        Workstation Authentication (V2). EKU and
#                        application policy now set together and
#                        deterministically. Added file logging, six
#                        aligned log helpers, $DryRun default, HTML email
#                        report, safe AD property reads, CA-host awareness
#                        for publication, and removed runtime self-lint.
#   2.0.0 - 2026-06-17 - Rebuilt the PKI engine on the supported CertEnroll
#                        IX509CertificateTemplateWritable COM path plus the
#                        PSPKI module. Removed raw New-ADObject template and
#                        OID creation, manual OID minting, the hand-built
#                        attribute hashtable, the ADCS period byte math, the
#                        ADSI security-descriptor edits, and the
#                        ActiveDirectory / ADCSAdministration dependencies.
#                        The platform now auto-generates the template OID on
#                        Commit. Permissions use PSPKI template ACL cmdlets;
#                        publication uses PSPKI CA cmdlets. Drift validation
#                        reads the PSPKI managed template model defensively.
#   2.1.0 - 2026-06-17 - Added a quiet auto-install of the PSPKI module from
#                        the PowerShell Gallery when it is missing: TLS 1.2 is
#                        enforced, the NuGet provider is bootstrapped, the
#                        progress bar is silenced, and the install scope is
#                        chosen by elevation (AllUsers when elevated, else
#                        CurrentUser). New -AutoInstallModules switch (default
#                        true) gates the behavior for locked-down hosts.
# =====================================================================

[CmdletBinding()]
param
(
    [Parameter(Mandatory = $false)]
    [string]$BaseTemplateName = 'Workstation Authentication',

    [Parameter(Mandatory = $false)]
    [ValidatePattern('^[A-Za-z0-9_\-]+$')]
    [string]$NewTemplateShortName = '__UH__MDM__WiFiDevice__SAN__2048__V1',

    [Parameter(Mandatory = $false)]
    [string]$NewTemplateDisplayName = 'UH-MDM-WiFi-DeviceCert',

    [Parameter(Mandatory = $false)]
    [switch]$PublishToCA,

    [Parameter(Mandatory = $false)]
    [switch]$IncludeServerAuthentication,

    [Parameter(Mandatory = $false)]
    [string]$EnrollmentPrincipal,

    [Parameter(Mandatory = $false)]
    [switch]$GrantAutoEnroll,

    [Parameter(Mandatory = $false)]
    [switch]$ValidateOnly,

    [Parameter(Mandatory = $false)]
    [bool]$DryRun = $true,

    [Parameter(Mandatory = $false)]
    [bool]$AutoInstallModules = $true
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ============================================================
# REGION: VARIABLES
# ============================================================

# --- Script identity / timestamps ---
$ScriptName   = 'New-UHMDMWiFiTemplate'
$FriendlyDate = Get-Date -Format 'MM-dd-yyyy'
$RunTimestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

# --- Logging paths ---
$LogDir  = Join-Path -Path $env:ProgramData -ChildPath 'UH\Logs'
$LogFile = Join-Path -Path $LogDir -ChildPath ('{0}_{1}.log' -f $ScriptName, (Get-Date -Format 'yyyyMMdd'))

# --- Console icon toggle ---
$UseConsoleIcons = $false
$ConsoleIcons = @{
    INFO   = [char]::ConvertFromUtf32(0x2139)    # information
    OK     = [char]::ConvertFromUtf32(0x2705)    # check mark
    WARN   = [char]::ConvertFromUtf32(0x26A0)    # warning sign
    ERROR  = [char]::ConvertFromUtf32(0x274C)    # cross mark
    DRYRUN = [char]::ConvertFromUtf32(0x1F7E1)   # yellow circle
}

# --- SMTP / email (open relay, no authentication) ---
$SmtpServer = 'smtp.uhhs.com'
$SmtpPort   = 25
$MailFrom   = 'Certerator@uhhs.com'
$MailTo     = @(
    'Alan.Phillips@UHhospitals.org'
    'Jeffrey.Altomari@UHhospitals.org'
)

# --- Issuing CA (CAHostName\CA Common Name) used for publication ---
$CAConfig = 'uhpkisub03\University Hospitals Sub CA 3'

# --- Module dependency ---
$PSPKIModuleName = 'PSPKI'

# --- Template policy values (inherited from the V2 base unless overridden) ---
$MinimumKeySize = 2048           # RSA minimum; Workstation Authentication base already meets this
$ValidityDays   = 365            # 1-year certificate validity (inherited from base)
$RenewalDays    = 42             # overlap / renewal window (inherited from base)
$DefaultKsp     = 'Microsoft Software Key Storage Provider'

# --- DNS domains (informational; SANs are supplied per-request by WS1 UEM) ---
$PrimaryDomain   = 'uhhs.com'
$AlternateDomain = 'uhhospitals.org'

# --- EKU / application policy OIDs ---
$EkuClientAuth = '1.3.6.1.5.5.7.3.2'
$EkuServerAuth = '1.3.6.1.5.5.7.3.1'

# --- CertEnroll COM ProgIDs (supported template authoring path) ---
$ComPolicyServer  = 'X509Enrollment.CX509EnrollmentPolicyActiveDirectory'
$ComWritableTmpl  = 'X509Enrollment.CX509CertificateTemplateADWritable'
$ComObjectIds     = 'X509Enrollment.CObjectIds'
$ComObjectId      = 'X509Enrollment.CObjectId'

# --- CertEnroll enum values used below ---
# X509CertificateEnrollmentContext::ContextAdministratorForceMachine
$EnrollContextAdminForceMachine = 3
# X509EnrollmentPolicyLoadOption::LoadOptionDefault
$LoadOptionDefault = 0
# CommitTemplateFlags::CommitFlagSaveTemplateGenerateOID (platform mints a new OID object)
$CommitFlagGenerateOID = 1
# X509CertificateTemplateSubjectNameFlag::SubjectEnrolleeSuppliesSubject
$SubjectSupplyInRequest = 1

# --- EnrollmentTemplateProperty IDs (CertEnroll certenroll.h) ---
# VERIFY: CommonName and FriendlyName are stable. Confirm EKUs and
# SubjectNameFlags against your build before production. The script
# defaults to -DryRun for exactly this reason.
$TemplateProp = @{
    CommonName       = 1     # TemplatePropCommonName
    FriendlyName     = 2     # TemplatePropFriendlyName
    EKUs             = 9     # TemplatePropEKUs              (VERIFY)
    SubjectNameFlags = 25    # TemplatePropSubjectNameFlags  (VERIFY)
}

# --- Action ledger for the email report ---
$Script:ActionLedger = New-Object System.Collections.Generic.List[pscustomobject]

# ============================================================
# REGION: LOGGING
# ============================================================

function Write-Log
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Line
    )

    try
    {
        if (-not (Test-Path -LiteralPath $LogDir))
        {
            New-Item -Path $LogDir -ItemType Directory -Force | Out-Null
        }

        Add-Content -LiteralPath $LogFile -Value $Line -Encoding UTF8
    }
    catch
    {
        # File logging must never break the run; surface to console only.
        Write-Host ("[LOGFAIL] Unable to write to {0}: {1}" -f $LogFile, $_.Exception.Message) -ForegroundColor DarkYellow
    }
}

function Write-ConsoleLine
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Level,

        [Parameter(Mandatory)]
        [string]$Tag,

        [Parameter(Mandatory)]
        [System.ConsoleColor]$Color,

        [Parameter(Mandatory)]
        [string]$Message
    )

    $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $icon  = ''

    if ($UseConsoleIcons -and $ConsoleIcons.ContainsKey($Level))
    {
        $icon = '{0} ' -f $ConsoleIcons[$Level]
    }

    $consoleText = '{0}[{1}] {2}{3}' -f $icon, $stamp, $Tag, $Message
    $fileText    = '[{0}] {1}{2}' -f $stamp, $Tag, $Message

    Write-Host $consoleText -ForegroundColor $Color
    Write-Log -Line $fileText
}

function Write-InfoMsg
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-ConsoleLine -Level 'INFO' -Tag '[INFO ] ' -Color Cyan -Message $Message
}

function Write-SuccessMsg
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-ConsoleLine -Level 'OK' -Tag '[OK   ] ' -Color Green -Message $Message
}

function Write-WarnMsg
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-ConsoleLine -Level 'WARN' -Tag '[WARN ] ' -Color Yellow -Message $Message
}

function Write-ErrorMsg
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-ConsoleLine -Level 'ERROR' -Tag '[ERROR] ' -Color Red -Message $Message
}

function Write-DryRunMsg
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-ConsoleLine -Level 'DRYRUN' -Tag '[DRYRUN] ' -Color Magenta -Message $Message
}

# ============================================================
# REGION: HELPERS
# ============================================================

function Get-AdProp
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [AllowNull()]
        $Object,

        [Parameter(Mandatory)]
        [string]$Name
    )

    if ($null -eq $Object)
    {
        return $null
    }

    $member = $Object.PSObject.Properties[$Name]

    if ($null -ne $member)
    {
        return $member.Value
    }

    return $null
}

function Add-LedgerEntry
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$Action,

        [Parameter(Mandatory)]
        [string]$Result,

        [Parameter(Mandatory = $false)]
        [string]$Detail = ''
    )

    $entry = [pscustomobject]@{
        Action = $Action
        Result = $Result
        Detail = $Detail
    }

    $Script:ActionLedger.Add($entry)
}

function Get-EmailSubject
{
    [CmdletBinding()]
    param()

    return ('{0} - {1}' -f $ScriptName, $FriendlyDate)
}

function Install-PSPKIModule
{
    [CmdletBinding()]
    param()

    Write-WarnMsg -Message ('Module [{0}] is not installed. Attempting a quiet install from the PowerShell Gallery.' -f $PSPKIModuleName)

    $previousProgress = $ProgressPreference
    $previousSecurity = [System.Net.ServicePointManager]::SecurityProtocol

    try
    {
        # PowerShell 5.1 defaults to protocols the gallery rejects, so TLS 1.2
        # must be enabled, and the progress bar is silenced (it also slows
        # downloads dramatically on 5.1).
        $ProgressPreference = 'SilentlyContinue'
        [System.Net.ServicePointManager]::SecurityProtocol =
            [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12

        # AllUsers when elevated (server / service context); CurrentUser otherwise.
        $identity    = [System.Security.Principal.WindowsIdentity]::GetCurrent()
        $principal   = New-Object System.Security.Principal.WindowsPrincipal -ArgumentList $identity
        $isElevated  = $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
        $installScope = if ($isElevated) { 'AllUsers' } else { 'CurrentUser' }

        Write-InfoMsg -Message ('Install scope resolved to [{0}] (elevated = {1}).' -f $installScope, $isElevated)

        # Bootstrap the NuGet provider so Install-Module does not prompt for it.
        $nuget = Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue
        if ((-not $nuget) -or ($nuget.Version -lt [version]'2.8.5.201'))
        {
            Write-InfoMsg -Message 'Bootstrapping NuGet package provider.'
            $nugetParams = @{
                Name           = 'NuGet'
                MinimumVersion = '2.8.5.201'
                Scope          = $installScope
                Force          = $true
                ErrorAction    = 'Stop'
            }
            Install-PackageProvider @nugetParams | Out-Null
        }

        # -Force suppresses the untrusted-repository confirmation prompt.
        $installParams = @{
            Name         = $PSPKIModuleName
            Scope        = $installScope
            Repository   = 'PSGallery'
            Force        = $true
            AllowClobber = $true
            Confirm      = $false
            ErrorAction  = 'Stop'
        }

        # -AcceptLicense only exists on newer PowerShellGet; add it when present.
        if ((Get-Command -Name Install-Module).Parameters.ContainsKey('AcceptLicense'))
        {
            $installParams['AcceptLicense'] = $true
        }

        Install-Module @installParams
        Write-SuccessMsg -Message ('Installed module [{0}] from the PowerShell Gallery.' -f $PSPKIModuleName)
    }
    finally
    {
        $ProgressPreference = $previousProgress
        [System.Net.ServicePointManager]::SecurityProtocol = $previousSecurity
    }
}

function Initialize-PSPKI
{
    [CmdletBinding()]
    param()

    if (Get-Module -Name $PSPKIModuleName)
    {
        return
    }

    $available = Get-Module -ListAvailable -Name $PSPKIModuleName |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if ($null -eq $available)
    {
        if (-not $AutoInstallModules)
        {
            throw ('Module [{0}] is not installed and -AutoInstallModules is disabled. Install it with: Install-Module {0} -Scope CurrentUser' -f $PSPKIModuleName)
        }

        Install-PSPKIModule

        $available = Get-Module -ListAvailable -Name $PSPKIModuleName |
            Sort-Object Version -Descending |
            Select-Object -First 1

        if ($null -eq $available)
        {
            throw ('Module [{0}] could not be installed automatically. Install it manually: Install-Module {0} -Scope CurrentUser' -f $PSPKIModuleName)
        }
    }

    Import-Module $PSPKIModuleName -ErrorAction Stop | Out-Null
    Write-SuccessMsg -Message ('Loaded module [{0}] version [{1}].' -f $available.Name, $available.Version)
}

# ============================================================
# REGION: COM CLONE ENGINE
# ============================================================

function Get-BaseTemplateComObject
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$BaseName
    )

    # Load the machine enrollment policy from Active Directory and walk the
    # returned IX509CertificateTemplates collection. The base is matched on
    # either its common name (cn) or its friendly (display) name, because
    # built-in templates frequently differ between the two (for example, the
    # cn of 'Workstation Authentication' is 'Workstation').
    $policy = New-Object -ComObject $ComPolicyServer
    $policy.Initialize($EnrollContextAdminForceMachine)
    $policy.LoadPolicy($LoadOptionDefault)

    $templates = $policy.GetTemplates()
    $count     = $templates.Count

    for ($i = 0; $i -lt $count; $i++)
    {
        $candidate = $templates.ItemByIndex($i)

        $cn = $candidate.Property($TemplateProp.CommonName)
        $fn = $candidate.Property($TemplateProp.FriendlyName)

        if (($cn -eq $BaseName) -or ($fn -eq $BaseName))
        {
            return $candidate
        }
    }

    throw ('Base template [{0}] was not found in the Active Directory enrollment policy.' -f $BaseName)
}

function New-EkuObjectIds
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string[]]$OidValues
    )

    $collection = New-Object -ComObject $ComObjectIds

    foreach ($value in $OidValues)
    {
        $oid = New-Object -ComObject $ComObjectId
        $oid.InitializeFromValue($value)
        $collection.Add($oid)
    }

    return $collection
}

function New-MdmWiFiTemplate
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$BaseName,

        [Parameter(Mandatory)]
        [string]$ShortName,

        [Parameter(Mandatory)]
        [string]$DisplayName,

        [Parameter(Mandatory)]
        [bool]$IncludeServerAuth
    )

    if ($DryRun)
    {
        Write-DryRunMsg -Message ('Would clone base [{0}] into new template [{1}] (display ''{2}'').' -f $BaseName, $ShortName, $DisplayName)
        Write-DryRunMsg -Message 'Would set subject name to supply-in-request and commit with platform-generated OID.'

        if ($IncludeServerAuth)
        {
            Write-DryRunMsg -Message 'Would set EKUs to Client + Server Authentication.'
        }
        else
        {
            Write-DryRunMsg -Message 'Would inherit Client Authentication EKU from the base.'
        }

        Add-LedgerEntry -Action 'Clone + commit template' -Result 'DryRun' -Detail $ShortName
        return $null
    }

    Write-InfoMsg -Message ('Loading base template [{0}] from the AD enrollment policy.' -f $BaseName)
    $baseCom = Get-BaseTemplateComObject -BaseName $BaseName

    Write-InfoMsg -Message 'Initializing a writable template from the base.'
    $writable = New-Object -ComObject $ComWritableTmpl
    $writable.Initialize($baseCom)

    # Identity overrides.
    $writable.Property($TemplateProp.CommonName)   = $ShortName
    $writable.Property($TemplateProp.FriendlyName) = $DisplayName

    # Subject is supplied in the request (MDM provides subject and SAN).
    $writable.Property($TemplateProp.SubjectNameFlags) = $SubjectSupplyInRequest

    # EKUs: inherit Client Authentication from the base unless Server
    # Authentication is also requested, in which case set both explicitly.
    if ($IncludeServerAuth)
    {
        $ekuCollection = New-EkuObjectIds -OidValues @($EkuClientAuth, $EkuServerAuth)
        $writable.Property($TemplateProp.EKUs) = $ekuCollection
        Write-InfoMsg -Message 'EKUs set to Client + Server Authentication.'
    }
    else
    {
        Write-InfoMsg -Message 'EKU inherited from base (Client Authentication).'
    }

    Write-InfoMsg -Message 'Committing the new template to Active Directory (platform-generated OID).'
    $writable.Commit($CommitFlagGenerateOID, $null)

    Write-SuccessMsg -Message ('Committed template [{0}].' -f $ShortName)
    Add-LedgerEntry -Action 'Clone + commit template' -Result 'Created' -Detail ('{0} from {1}' -f $ShortName, $BaseName)

    # Allow AD replication / policy cache a moment, then verify via PSPKI.
    Start-Sleep -Seconds 3
    $newTemplate = Get-CertificateTemplate -Name $ShortName -ErrorAction SilentlyContinue

    if (-not $newTemplate)
    {
        Start-Sleep -Seconds 5
        $newTemplate = Get-CertificateTemplate -Name $ShortName -ErrorAction SilentlyContinue
    }

    if (-not $newTemplate)
    {
        throw ('Template [{0}] was not found via PSPKI after commit.' -f $ShortName)
    }

    Write-SuccessMsg -Message 'Verified the new template is present in AD DS.'
    return $newTemplate
}

# ============================================================
# REGION: DRIFT VALIDATION
# ============================================================

function Get-TemplateFacts
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        $Template
    )

    # The PSPKI managed model exposes most settings under .Settings, but
    # property names vary slightly across module versions, so every read is
    # guarded and degrades to a null / empty value rather than throwing.
    $facts = [ordered]@{
        ShortName   = $null
        DisplayName = $null
        KeyLength   = $null
        SubjectName = $null
        Ekus        = @()
        Providers   = @()
    }

    try { $facts.ShortName   = Get-AdProp -Object $Template -Name 'Name' }        catch { }
    try { $facts.DisplayName = Get-AdProp -Object $Template -Name 'DisplayName' } catch { }

    $settings = Get-AdProp -Object $Template -Name 'Settings'

    if ($null -ne $settings)
    {
        try { $facts.KeyLength   = Get-AdProp -Object $settings -Name 'MinimalKeyLength' } catch { }
        try { $facts.SubjectName = [string](Get-AdProp -Object $settings -Name 'SubjectName') } catch { }

        $eku = Get-AdProp -Object $settings -Name 'EnhancedKeyUsage'
        if ($null -ne $eku)
        {
            try { $facts.Ekus = @($eku | ForEach-Object { Get-AdProp -Object $_ -Name 'Value' }) } catch { }
        }

        $crypto = Get-AdProp -Object $settings -Name 'Cryptography'
        if ($null -ne $crypto)
        {
            $cspList = Get-AdProp -Object $crypto -Name 'CSPList'
            if ($null -ne $cspList)
            {
                try { $facts.Providers = @($cspList) } catch { }
            }
        }
    }

    return $facts
}

function Test-TemplateDrift
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        $Template,

        [Parameter(Mandatory)]
        [string]$ExpectedDisplayName,

        [Parameter(Mandatory)]
        [bool]$ExpectedIncludeServerAuth
    )

    $facts    = Get-TemplateFacts -Template $Template
    $problems = New-Object System.Collections.Generic.List[string]

    if ([string]$facts.DisplayName -ne $ExpectedDisplayName)
    {
        $problems.Add(('displayName mismatch (existing=''{0}'', expected=''{1}'')' -f $facts.DisplayName, $ExpectedDisplayName))
    }

    if ($facts.SubjectName -notmatch 'EnrolleeSuppliesSubject')
    {
        $problems.Add(('subject name is ''{0}'', expected supply-in-request (EnrolleeSuppliesSubject)' -f $facts.SubjectName))
    }

    if ($null -ne $facts.KeyLength -and [int]$facts.KeyLength -lt $MinimumKeySize)
    {
        $problems.Add(('minimum key size is ''{0}'', expected >= {1}' -f $facts.KeyLength, $MinimumKeySize))
    }

    if ($EkuClientAuth -notin $facts.Ekus)
    {
        $problems.Add('Client Authentication EKU missing')
    }

    if ($ExpectedIncludeServerAuth -and ($EkuServerAuth -notin $facts.Ekus))
    {
        $problems.Add('Server Authentication EKU missing')
    }

    if ((-not $ExpectedIncludeServerAuth) -and ($EkuServerAuth -in $facts.Ekus))
    {
        $problems.Add('Server Authentication EKU present but not expected')
    }

    if (@($problems).Count -gt 0)
    {
        throw ('Template drift detected: {0}' -f ($problems -join ' | '))
    }

    Write-SuccessMsg -Message ('Existing template [{0}] passed drift check.' -f $facts.ShortName)
}

# ============================================================
# REGION: ACL / PUBLISH
# ============================================================

function Grant-TemplateEnrollmentRights
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$ShortName,

        [Parameter(Mandatory)]
        [string]$Principal,

        [Parameter(Mandatory)]
        [bool]$AddAutoEnroll
    )

    # PSPKI ACL cmdlet parameter names can vary by module version; the
    # pipeline idiom below is the documented form. VERIFY against your build.
    $template = Get-CertificateTemplate -Name $ShortName

    if ($AddAutoEnroll)
    {
        $acl = $template |
            Get-CertificateTemplateAcl |
            Add-CertificateTemplateAcl -User $Principal -AccessType Allow -AccessMask Read, Enroll, Autoenroll
    }
    else
    {
        $acl = $template |
            Get-CertificateTemplateAcl |
            Add-CertificateTemplateAcl -User $Principal -AccessType Allow -AccessMask Read, Enroll
    }

    $acl | Set-CertificateTemplateAcl | Out-Null
}

function Publish-TemplateToCA
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$ShortName
    )

    $caHost = ($CAConfig -split '\\')[0]

    Write-InfoMsg -Message ('Connecting to issuing CA [{0}].' -f $caHost)
    $ca = Connect-CertificationAuthority -ComputerName $caHost

    $alreadyPublished = Get-CATemplate -CertificationAuthority $ca |
        Where-Object { $_.Name -eq $ShortName }

    if ($alreadyPublished)
    {
        Write-SuccessMsg -Message ('Template [{0}] is already published on [{1}].' -f $ShortName, $caHost)
        Add-LedgerEntry -Action 'Publish to CA' -Result 'Already published' -Detail $ShortName
        return
    }

    Get-CertificateTemplate -Name $ShortName |
        Add-CATemplate -CertificationAuthority $ca

    Write-SuccessMsg -Message ('Published template [{0}] to [{1}].' -f $ShortName, $caHost)
    Add-LedgerEntry -Action 'Publish to CA' -Result 'Published' -Detail $ShortName
}

# ============================================================
# REGION: VALIDATION-ONLY MODE
# ============================================================

function Invoke-TemplateValidationOnly
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$ShortName,

        [Parameter(Mandatory)]
        [string]$ExpectedDisplayName,

        [Parameter(Mandatory)]
        [bool]$ExpectedIncludeServerAuth
    )

    Write-InfoMsg -Message ('VALIDATE-ONLY mode enabled. Looking up template [{0}].' -f $ShortName)

    $template = Get-CertificateTemplate -Name $ShortName -ErrorAction SilentlyContinue
    if (-not $template)
    {
        $template = Get-CertificateTemplate -DisplayName $ExpectedDisplayName -ErrorAction SilentlyContinue
    }

    if (-not $template)
    {
        throw ('VALIDATE-ONLY failed. Template [{0}] / [{1}] was not found.' -f $ShortName, $ExpectedDisplayName)
    }

    Test-TemplateDrift -Template $template -ExpectedDisplayName $ExpectedDisplayName -ExpectedIncludeServerAuth $ExpectedIncludeServerAuth

    $facts = Get-TemplateFacts -Template $template

    Write-InfoMsg -Message ('Short Name          : {0}' -f $facts.ShortName)
    Write-InfoMsg -Message ('Display Name        : {0}' -f $facts.DisplayName)
    Write-InfoMsg -Message ('Subject Name Flags  : {0}' -f $facts.SubjectName)
    Write-InfoMsg -Message ('Minimum Key Size    : {0}' -f $facts.KeyLength)
    Write-InfoMsg -Message ('EKUs                : {0}' -f ($facts.Ekus -join ', '))
    Write-InfoMsg -Message ('Provider(s)         : {0}' -f ($facts.Providers -join ', '))
    Write-InfoMsg -Message ('Server Auth Expected: {0}' -f $ExpectedIncludeServerAuth)

    Add-LedgerEntry -Action 'Validate template' -Result 'Passed' -Detail $facts.ShortName
    Write-SuccessMsg -Message ('VALIDATE-ONLY PASSED for template [{0}].' -f $facts.ShortName)
}

# ============================================================
# REGION: EMAIL REPORT
# ============================================================

function Build-HtmlReport
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$ModeText
    )

    $rows = ''

    foreach ($item in $Script:ActionLedger)
    {
        $color = switch ($item.Result)
        {
            'Created'           { '#1a7f37' }
            'Published'         { '#1a7f37' }
            'Passed'            { '#1a7f37' }
            'Already published' { '#0a66c2' }
            'DryRun'            { '#9a3412' }
            'Skipped'           { '#9a3412' }
            default             { '#333333' }
        }

        $rows += ('<tr><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;">{0}</td><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;color:{1};font-weight:600;">{2}</td><td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;color:#444;">{3}</td></tr>' -f $item.Action, $color, $item.Result, $item.Detail)
    }

    if (-not $rows)
    {
        $rows = '<tr><td colspan="3" style="padding:6px 12px;color:#777;">No actions recorded.</td></tr>'
    }

    $ekuText = if ($IncludeServerAuthentication) { 'Client + Server Authentication' } else { 'Client Authentication' }

    $html = @"
<html>
<body style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;color:#222;">
  <h2 style="color:#0b3d6e;margin-bottom:4px;">UH MDM / WiFi Certificate Template</h2>
  <div style="color:#666;margin-bottom:16px;">$ModeText &mdash; $RunTimestamp</div>

  <table style="border-collapse:collapse;margin-bottom:18px;">
    <tr><td style="padding:4px 12px;color:#666;">Short Name</td><td style="padding:4px 12px;font-weight:600;">$NewTemplateShortName</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Display Name</td><td style="padding:4px 12px;font-weight:600;">$NewTemplateDisplayName</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Base Template</td><td style="padding:4px 12px;">$BaseTemplateName</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Engine</td><td style="padding:4px 12px;">CertEnroll IX509CertificateTemplateWritable + PSPKI</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">EKU</td><td style="padding:4px 12px;">$ekuText</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Minimum Key Size</td><td style="padding:4px 12px;">$MinimumKeySize</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Issuing CA</td><td style="padding:4px 12px;">$CAConfig</td></tr>
    <tr><td style="padding:4px 12px;color:#666;">Run By</td><td style="padding:4px 12px;">$env:USERDOMAIN\$env:USERNAME on $env:COMPUTERNAME</td></tr>
  </table>

  <table style="border-collapse:collapse;width:100%;max-width:760px;">
    <thead>
      <tr style="background:#0b3d6e;color:#fff;">
        <th style="padding:8px 12px;text-align:left;">Action</th>
        <th style="padding:8px 12px;text-align:left;">Result</th>
        <th style="padding:8px 12px;text-align:left;">Detail</th>
      </tr>
    </thead>
    <tbody>
      $rows
    </tbody>
  </table>

  <p style="color:#999;font-size:12px;margin-top:18px;">Generated by $ScriptName.ps1</p>
</body>
</html>
"@

    return $html
}

function Send-ReportEmail
{
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory)]
        [string]$HtmlBody
    )

    $mailParams = @{
        SmtpServer = $SmtpServer
        Port       = $SmtpPort
        From       = $MailFrom
        To         = $MailTo
        Subject    = (Get-EmailSubject)
        Body       = $HtmlBody
        BodyAsHtml = $true
    }

    Send-MailMessage @mailParams
    Write-SuccessMsg -Message ('Report email sent to: {0}' -f ($MailTo -join ', '))
}

# ============================================================
# REGION: MAIN
# ============================================================

function Invoke-Main
{
    [CmdletBinding()]
    param()

    Write-InfoMsg -Message ('{0} starting (DryRun = {1}).' -f $ScriptName, $DryRun)

    Initialize-PSPKI

    if ($ValidateOnly)
    {
        Invoke-TemplateValidationOnly -ShortName $NewTemplateShortName -ExpectedDisplayName $NewTemplateDisplayName -ExpectedIncludeServerAuth $IncludeServerAuthentication.IsPresent
        return 'Validate-only'
    }

    Write-InfoMsg -Message ('Checking whether template [{0}] already exists.' -f $NewTemplateShortName)
    $existing = Get-CertificateTemplate -Name $NewTemplateShortName -ErrorAction SilentlyContinue
    if (-not $existing)
    {
        $existing = Get-CertificateTemplate -DisplayName $NewTemplateDisplayName -ErrorAction SilentlyContinue
    }

    if ($existing)
    {
        Write-WarnMsg -Message 'Template already exists. Running drift check instead of creating a duplicate.'

        Test-TemplateDrift -Template $existing -ExpectedDisplayName $NewTemplateDisplayName -ExpectedIncludeServerAuth $IncludeServerAuthentication.IsPresent
        Add-LedgerEntry -Action 'Clone + commit template' -Result 'Skipped' -Detail 'Already exists; passed drift check.'

        $existingShort = Get-AdProp -Object $existing -Name 'Name'

        if ($PublishToCA)
        {
            if ($DryRun)
            {
                Write-DryRunMsg -Message ('Would publish existing template [{0}] to CA.' -f $existingShort)
                Add-LedgerEntry -Action 'Publish to CA' -Result 'DryRun' -Detail $existingShort
            }
            else
            {
                Publish-TemplateToCA -ShortName $existingShort
            }
        }

        Write-SuccessMsg -Message 'No creation performed; template already exists and passed drift check.'
        return 'Drift check (existing template)'
    }

    $newTemplate = New-MdmWiFiTemplate -BaseName $BaseTemplateName -ShortName $NewTemplateShortName -DisplayName $NewTemplateDisplayName -IncludeServerAuth $IncludeServerAuthentication.IsPresent

    if ($EnrollmentPrincipal)
    {
        if ($DryRun)
        {
            $autoText = if ($GrantAutoEnroll) { ' + AutoEnroll' } else { '' }
            Write-DryRunMsg -Message ('Would grant Read + Enroll{0} to [{1}].' -f $autoText, $EnrollmentPrincipal)
            Add-LedgerEntry -Action 'Grant enrollment rights' -Result 'DryRun' -Detail $EnrollmentPrincipal
        }
        elseif ($null -ne $newTemplate)
        {
            Write-InfoMsg -Message ('Granting Read + Enroll rights to [{0}].' -f $EnrollmentPrincipal)
            Grant-TemplateEnrollmentRights -ShortName $NewTemplateShortName -Principal $EnrollmentPrincipal -AddAutoEnroll $GrantAutoEnroll.IsPresent

            Write-SuccessMsg -Message ('Granted template permissions to [{0}].' -f $EnrollmentPrincipal)
            Add-LedgerEntry -Action 'Grant enrollment rights' -Result 'Created' -Detail $EnrollmentPrincipal
        }
    }

    if ($PublishToCA)
    {
        if ($DryRun)
        {
            Write-DryRunMsg -Message ('Would publish template [{0}] to CA [{1}].' -f $NewTemplateShortName, $CAConfig)
            Add-LedgerEntry -Action 'Publish to CA' -Result 'DryRun' -Detail $NewTemplateShortName
        }
        else
        {
            Publish-TemplateToCA -ShortName $NewTemplateShortName
        }
    }

    if ($DryRun)
    {
        return 'Dry run (no changes made)'
    }

    return 'Template created'
}

# ============================================================
# REGION: ENTRY POINT
# ============================================================

$modeResult = 'Failed'

try
{
    $modeResult = Invoke-Main
}
catch
{
    Write-ErrorMsg -Message $_.Exception.Message
    Add-LedgerEntry -Action 'Run' -Result 'Skipped' -Detail $_.Exception.Message
    $modeResult = ('Error: {0}' -f $_.Exception.Message)
}
finally
{
    try
    {
        $reportHtml = Build-HtmlReport -ModeText $modeResult
        Send-ReportEmail -HtmlBody $reportHtml
    }
    catch
    {
        Write-ErrorMsg -Message ('Failed to send report email: {0}' -f $_.Exception.Message)
    }
}